// <auto-generated />
using System;
using Api_DnD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_DnD.Migrations
{
    [DbContext(typeof(DNDContext))]
    [Migration("20230918213452_Key")]
    partial class Key
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Api_DnD.Model.Arme", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BonusForce")
                        .HasColumnType("int");

                    b.Property<int>("BonusJet")
                        .HasColumnType("int");

                    b.Property<int>("EnchantementId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("EnchantementId");

                    b.ToTable("Arme", (string)null);
                });

            modelBuilder.Entity("Api_DnD.Model.Armure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Ac")
                        .HasColumnType("int");

                    b.Property<bool>("DexBonus")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EnchantId")
                        .HasColumnType("int");

                    b.Property<int>("MaxDexMod")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("StealthDisadvantage")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EnchantId");

                    b.ToTable("Armure", (string)null);
                });

            modelBuilder.Entity("Api_DnD.Model.Classes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("hitDie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("primaryAbility")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Classes", (string)null);
                });

            modelBuilder.Entity("Api_DnD.Model.Enchantement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Modif")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Enchantement", (string)null);
                });

            modelBuilder.Entity("Api_DnD.Model.Key", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Key", (string)null);
                });

            modelBuilder.Entity("Api_DnD.Model.PNJ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Barbe")
                        .HasColumnType("int");

                    b.Property<int>("Bouche")
                        .HasColumnType("int");

                    b.Property<int>("Cheveux")
                        .HasColumnType("int");

                    b.Property<int>("Nez")
                        .HasColumnType("int");

                    b.Property<string>("Quête")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Sourcil")
                        .HasColumnType("int");

                    b.Property<int>("Tete")
                        .HasColumnType("int");

                    b.Property<int>("Yeux1")
                        .HasColumnType("int");

                    b.Property<int>("Yeux2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PNJ", (string)null);
                });

            modelBuilder.Entity("Api_DnD.Model.Perso", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("armeId")
                        .HasColumnType("int");

                    b.Property<int>("armureId")
                        .HasColumnType("int");

                    b.Property<string>("bonds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("classesid")
                        .HasColumnType("int");

                    b.Property<string>("flaws")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ideal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("inspiration")
                        .HasColumnType("int");

                    b.Property<int>("niv")
                        .HasColumnType("int");

                    b.Property<string>("personalitetrait")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("raceId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("armeId");

                    b.HasIndex("armureId");

                    b.HasIndex("classesid");

                    b.HasIndex("raceId");

                    b.ToTable("Perso", (string)null);
                });

            modelBuilder.Entity("Api_DnD.Model.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BonusConsti")
                        .HasColumnType("int");

                    b.Property<int>("BonusDex")
                        .HasColumnType("int");

                    b.Property<int>("BonusForce")
                        .HasColumnType("int");

                    b.Property<int>("BonusIntel")
                        .HasColumnType("int");

                    b.Property<int>("BonusPV")
                        .HasColumnType("int");

                    b.Property<int>("BonusWisdom")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Race", (string)null);
                });

            modelBuilder.Entity("Api_DnD.Model.Skill", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Persoid")
                        .HasColumnType("int");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("Persoid");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("Api_DnD.Model.Arme", b =>
                {
                    b.HasOne("Api_DnD.Model.Enchantement", "Enchantement")
                        .WithMany()
                        .HasForeignKey("EnchantementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enchantement");
                });

            modelBuilder.Entity("Api_DnD.Model.Armure", b =>
                {
                    b.HasOne("Api_DnD.Model.Enchantement", "Enchant")
                        .WithMany()
                        .HasForeignKey("EnchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enchant");
                });

            modelBuilder.Entity("Api_DnD.Model.Perso", b =>
                {
                    b.HasOne("Api_DnD.Model.Arme", "arme")
                        .WithMany()
                        .HasForeignKey("armeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_DnD.Model.Armure", "armure")
                        .WithMany()
                        .HasForeignKey("armureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_DnD.Model.Classes", "classes")
                        .WithMany()
                        .HasForeignKey("classesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api_DnD.Model.Race", "race")
                        .WithMany()
                        .HasForeignKey("raceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("arme");

                    b.Navigation("armure");

                    b.Navigation("classes");

                    b.Navigation("race");
                });

            modelBuilder.Entity("Api_DnD.Model.Skill", b =>
                {
                    b.HasOne("Api_DnD.Model.Perso", null)
                        .WithMany("skills")
                        .HasForeignKey("Persoid");
                });

            modelBuilder.Entity("Api_DnD.Model.Perso", b =>
                {
                    b.Navigation("skills");
                });
#pragma warning restore 612, 618
        }
    }
}
